- id: pymetrica
  name: pymetrica
  entry: pymetrica-run-all .
  language: python
  require_serial: true
  pass_filenames: false

- id: pymetrica-aloc
  name: pymetrica aloc
  entry: pymetrica-aloc .
  language: python
  require_serial: true
  pass_filenames: false

- id: pymetrica-cc
  name: pymetrica cc
  entry: pymetrica-cc .
  language: python
  require_serial: true
  pass_filenames: false

- id: pymetrica-hv
  name: pymetrica hv
  entry: pymetrica-hv .
  language: python
  require_serial: true
  pass_filenames: false

- id: pymetrica-po
  name: pymetrica po
  entry: pymetrica-po .
  language: python
  require_serial: true
  pass_filenames: false

- id: pymetrica-mc
  name: pymetrica mc
  entry: pymetrica-mc .
  language: python
  require_serial: true
  pass_filenames: false
