- id: pymetrica
  name: pymetrica
  entry: pymetrica-run-all --report-type BASIC_HOOK
  language: python
  require_serial: true
  pass_filenames: false

- id: pymetrica-aloc
  name: pymetrica aloc
  entry: pymetrica-aloc --report-type BASIC_HOOK
  language: python
  require_serial: true
  pass_filenames: false

- id: pymetrica-cc
  name: pymetrica cc
  entry: pymetrica-cc --report-type BASIC_HOOK
  language: python
  require_serial: true
  pass_filenames: false

- id: pymetrica-hv
  name: pymetrica hv
  entry: pymetrica-hv --report-type BASIC_HOOK
  language: python
  require_serial: true
  pass_filenames: false

- id: pymetrica-po
  name: pymetrica po
  entry: pymetrica-po --report-type BASIC_HOOK
  language: python
  require_serial: true
  pass_filenames: false

- id: pymetrica-mc
  name: pymetrica mc
  entry: pymetrica-mc --report-type BASIC_HOOK
  language: python
  require_serial: true
  pass_filenames: false
